[project]
name = "offset-poly"
version = "0.3.0"
description = "offset a polyline or polygon in 2D space"
authors = [{ name = "Shay Hill", email = "shay_public@hotmail.com" }]
license = {text = "MIT"}
readme = "README.md"
# packages = [{include = "offset_poly"}]

# [tool.poetry.dependencies]
requires-python = ">=3.9"
dependencies = ["vec2_math ~= 0.1.0"]

[project.optional-dependencies]
dev = [
    "pytest ~= 7.4.0",
    "commitizen",
    "pre-commit"
]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.3.0"
tag_format = "$version"
major-version-zero = true
version_files = [
    "pyproject.toml:^version"
]


[tool.pyright]
include = ["src"]
exclude = ["**/__pycache__.py"]

pythonVersion = "3.9"
pythonPlatform = "Any"

typeCheckingMode = "strict"
reportShadowedImports = true
reportCallInDefaultInitializer = true
reportImplicitStringConcatenation = true
# reportMissingSuperCall = true
reportPropertyTypeMismatch = true
reportUninitializedInstanceVariable = true
reportUnnecessaryTypeIgnoreComment = true
reportUnusedCallResult = true

venvPath = "."
venv = "./venv"
